# Generated by Django 3.1.5 on 2021-02-13 18:05

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210210_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=products.models.image_upload_to),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
